package com.myproject.hospitalaplication.model;

public enum Department {
    Acil_tıp,
    Adli_tıp,
    Aile_hekimliği,
    Çocuk_ve_ergen_psikiyatrisi,
    Çocuk_hastalıkları,
    Dermatoloji,
    Fiziksel_tıp_ve_rehabilitasyon,
    Enfeksiyon_hastalıkları,
    Göğüs_hastalıkları,
    Halk_sağlığı,
    Dahiliye,
    Kardiyoloji,
    Nöroloji,
    Nükleer_tıp,
    Radyasyon_onkolojisi,
    Radyoloji,
    Psikiyatri,
    Spor_hekimliği,
    Genetik,
    Cerrahi_Tıp_Bilimleri,
    Anesteziyoloji_ve_reanimasyon,
    Beyin_ve_sinir_cerrahisi,
    Çocuk_cerrahisi,
    Genel_cerrahi,
    Göğüs_cerrahisi,
    Göz_hastalıkları,
    Kadın_Hastalıkları_ve_Doğum_hastalıkları,
    Kulak_burun_boğaz,
    Kalp_ve_Damar_Cerrahisi,
    Ortopedi_ve_Travmatoloji,
    Plastik_rekonstrüktif_ve_estetik_cerrahi,
    Üroloji,
    Tıbbi_Patoloji,
}
